sudo: required

branches:
  only:
  - master

services:
- docker

dist: trusty

env:
- DOCKER_IMAGE=strimr/track-metadata

script:
- echo "Hello World"
- ls -ls
- cat pom.xml
- mvn help:evaluate -Dexpression='project.version' -q -DforceStdout
- export PROJECT_VERSION=$(mvn help:evaluate -Dexpression='project.version' -q -DforceStdout)
- docker build  -t "$DOCKER_IMAGE:$TRAVIS_COMMIT" . #-t "$DOCKER_IMAGE:$PROJECT_VERSION"

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"